name: Nightly Python Script Run

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight every day
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

env:
  PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
  PINECONE_ENVIRONMENT: 'gcp-starter'
  PINECONE_INDEX_NAME: 'carenet'

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Specify the Python version

    - name: Cache pip packages
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f apps/crawler-feeds/requirements.txt ]; then pip install -r apps/crawler-feeds/requirements.txt; fi

    - name: Run script
      run: python apps/crawler-feeds/src/app.py  # Replace with your script's path
      env:
        PINECONE_ENVIRONMENT: ${{ env.PINECONE_ENVIRONMENT }}
        PINECONE_INDEX_NAME: ${{ env.PINECONE_INDEX_NAME }}
        PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
        PYTHONPATH: .
